Added node, less and compress

diff --git a/bin/steps/collectstatic b/bin/steps/collectstatic
--- a/bin/steps/collectstatic
+++ b/bin/steps/collectstatic
@@ -20,6 +20,14 @@ if [ ! "$DISABLE_COLLECTSTATIC" ] && [ -f "$MANAGE_FILE" ]; then
     # Compile assets if collectstatic appears to be kosher.
     if [ "$RUN_COLLECTSTATIC" ]; then
 
+        echo "-----> Compressing static files"
+        python $MANAGE_FILE compress --force 2>&1 | indent
+
+        [ $? -ne 0 ] && {
+            echo " !     Error running manage.py compress  More info:"
+            echo "       http://devcenter.heroku.com/articles/django-assets"
+        }
+
         echo "-----> Collecting static files"
         python $MANAGE_FILE collectstatic --noinput  2>&1 | sed '/^Copying/d;/^$/d;/^ /d' | indent
 
